### ISSUE TITLE
초기 환경설정

### ISSUE THREAD

**Issue by SL313** [SL313/wanted-pre-onboarding-backend#1]
### 📃 Description
엔드포인트 구현 전 환경설정을 위한 issue

### ✔ Todo List
- [x] git 연결
- [x] mysql database 생성 및 연결
- [x] readme.md 파일 생성
- [x] 기능 및 branch 설계
- [x] database entity 설계
