### ISSUE TITLE
feature/user 기능

### ISSUE THREAD

**Issue by SL313** [SL313/wanted-pre-onboarding-backend#2]
### 📃 Description

- 회원가입 엔드포인트
- 로그인 엔드포인트

### ✔ Todo List
- [ ] 이메일 @ 포함 (유효성 검사)
- [ ] 비밀번호 8자 이상 (유효성 검사)
- [ ] 비밀번호 암호화 저장
- [ ] 로그인 시 사용자 인증 과정
- [ ] 로그인 시 JWT 발급 후 반환 과정
